Vagrant.configure("2") do |config|
    config.vm.box = "spox/ubuntu-arm"
    config.vm.box_version = "1.0.0"
    config.vm.network "private_network", ip:"192.168.56.21"
    config.vm.network "public_network"
    config.vm.synced_folder "/Users/yashrajgarnayak/Desktop/vms/ubuntu-2", "/home/vagrant/"
    config.vm.provider "vmware_desktop" do |vb|
        vb.ssh_info_public = true
        vb.gui = true
        vb.memory = "1200"
        vb.cpus = "2"
    end
end
